### ISSUE TITLE
Issue in running code for per-recording classification.

### ISSUE THREAD

**Issue by rahuls321** [JackAndCole/Obstructive-Sleep-Apnea-Detection-Using-Convolutional-Neural-Network-CNN-#1]
Thanks for providing the code. 

It works fine in case of per-segment SA detection. Could you please tell me the procedure for per-recording classification as well?

Thanks in advance!!

**Comment by JackAndCole** [comment]
The per-recording results are based on the per-segment results to calculate the AHI. If AHI is greater 5 is taken as SA patient. Compared the results with "additional-information.txt", it is easier to calculate the accuracy and SE and SP. I have uploaded the calculation code of per-recording to the "utils" folder.

**Comment by rahuls321** [comment]
Thanks, I got it. @JackAndCole
